knp_paginator:
    page_range: 5                       # nombre de liens de page à afficher
    default_options:
        page_name: page                 # nom du paramètre de page 
        sort_field_name: sort           # nom du paramètre de tri
        sort_direction_name: direction  # nom du paramètre de direction
        distinct: true                  # assurer des résultats distincts
        filter_field_name: filterField # nom du paramètre de filtre
        filter_value_name: filterValue # nom de la valeur de filtre
    template:
        pagination: 'pagination/banking_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # tri
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filtrage
