vich_uploader:
    db_driver: orm

    mappings:
        profile_pictures:
            uri_prefix: /uploads/profile_pictures
            upload_destination: '%kernel.project_dir%/public/uploads/profile_pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        kyc_documents:
            uri_prefix: /uploads/kyc_documents
            upload_destination: '%kernel.project_dir%/public/uploads/kyc_documents'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
