<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250923222946 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE accounts (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, account_number VARCHAR(20) NOT NULL, iban VARCHAR(34) NOT NULL, balance NUMERIC(15, 2) NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, currency VARCHAR(3) NOT NULL, overdraft_limit NUMERIC(15, 2) DEFAULT NULL, interest_rate NUMERIC(5, 4) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', closed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_CAC89EACB1A4D127 (account_number), UNIQUE INDEX UNIQ_CAC89EACFAD56E62 (iban), INDEX IDX_CAC89EAC7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE amortization_schedule (id INT AUTO_INCREMENT NOT NULL, credit_application_id INT NOT NULL, month SMALLINT NOT NULL, payment_date DATE NOT NULL, monthly_payment NUMERIC(10, 2) NOT NULL, principal_payment NUMERIC(10, 2) NOT NULL, interest_payment NUMERIC(10, 2) NOT NULL, remaining_amount NUMERIC(10, 2) NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_124FDE36C9F772CD (credit_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bank_accounts (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, account_name VARCHAR(255) NOT NULL, iban VARCHAR(34) NOT NULL, bank_name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_FB88842BA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE card_oppositions (id INT AUTO_INCREMENT NOT NULL, card_id INT NOT NULL, requested_by_id INT NOT NULL, processed_by_id INT DEFAULT NULL, reason VARCHAR(50) NOT NULL, description VARCHAR(1000) DEFAULT NULL, status VARCHAR(20) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', reference VARCHAR(20) NOT NULL, new_card_requested TINYINT(1) NOT NULL, UNIQUE INDEX UNIQ_89A0F8C2AEA34913 (reference), INDEX IDX_89A0F8C24ACC9A20 (card_id), INDEX IDX_89A0F8C24DA1E751 (requested_by_id), INDEX IDX_89A0F8C22FFD4FD3 (processed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE card_subscriptions (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, account_id INT NOT NULL, processed_by_id INT DEFAULT NULL, card_id INT DEFAULT NULL, card_brand VARCHAR(20) NOT NULL, card_type VARCHAR(20) NOT NULL, status VARCHAR(20) NOT NULL, reason VARCHAR(500) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', reference VARCHAR(50) NOT NULL, activation_fee NUMERIC(8, 2) DEFAULT NULL, monthly_fee NUMERIC(8, 2) DEFAULT NULL, daily_limit NUMERIC(10, 2) DEFAULT NULL, monthly_limit NUMERIC(10, 2) DEFAULT NULL, credit_limit NUMERIC(12, 2) DEFAULT NULL, UNIQUE INDEX UNIQ_740D4320AEA34913 (reference), INDEX IDX_740D4320A76ED395 (user_id), INDEX IDX_740D43209B6B5FBA (account_id), INDEX IDX_740D43202FFD4FD3 (processed_by_id), UNIQUE INDEX UNIQ_740D43204ACC9A20 (card_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE cards (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, card_number VARCHAR(19) NOT NULL, cardholder_name VARCHAR(100) NOT NULL, expiry_date DATE NOT NULL, cvv VARCHAR(4) NOT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, daily_limit NUMERIC(15, 2) DEFAULT NULL, monthly_limit NUMERIC(15, 2) DEFAULT NULL, credit_limit NUMERIC(15, 2) DEFAULT NULL, daily_spent NUMERIC(15, 2) NOT NULL, monthly_spent NUMERIC(15, 2) NOT NULL, contactless TINYINT(1) NOT NULL, online_payments TINYINT(1) NOT NULL, international_payments TINYINT(1) NOT NULL, pin_attempts INT DEFAULT NULL, last_used_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', blocked_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', settings JSON DEFAULT NULL, UNIQUE INDEX UNIQ_4C258FDE4AF4C20 (card_number), INDEX IDX_4C258FD9B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_settings (id INT AUTO_INCREMENT NOT NULL, company_name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, email VARCHAR(255) NOT NULL, website VARCHAR(255) DEFAULT NULL, siret VARCHAR(50) DEFAULT NULL, logo_base64 LONGTEXT DEFAULT NULL, legal_mention VARCHAR(500) DEFAULT NULL, updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contract_fees (id INT AUTO_INCREMENT NOT NULL, credit_application_id INT NOT NULL, name VARCHAR(100) NOT NULL, amount NUMERIC(10, 2) NOT NULL, INDEX IDX_C8E68F04C9F772CD (credit_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contract_subscriptions (id INT AUTO_INCREMENT NOT NULL, card_subscription_id INT NOT NULL, status VARCHAR(20) NOT NULL, card_fees NUMERIC(8, 2) NOT NULL, daily_limit NUMERIC(10, 2) DEFAULT NULL, monthly_limit NUMERIC(10, 2) DEFAULT NULL, credit_limit NUMERIC(12, 2) DEFAULT NULL, general_conditions LONGTEXT DEFAULT NULL, specific_conditions LONGTEXT DEFAULT NULL, contract_pdf_path VARCHAR(255) DEFAULT NULL, signed_contract_pdf_path VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', sent_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', signed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', reference VARCHAR(50) NOT NULL, signature_data LONGTEXT DEFAULT NULL, signer_ip VARCHAR(100) DEFAULT NULL, signer_user_agent VARCHAR(500) DEFAULT NULL, UNIQUE INDEX UNIQ_852C0BD9AEA34913 (reference), UNIQUE INDEX UNIQ_852C0BD9F43F9851 (card_subscription_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contrat_assurance (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, demande_devis_id INT NOT NULL, numero_contrat VARCHAR(50) NOT NULL, type_assurance VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, prime_mensuelle NUMERIC(8, 2) NOT NULL, montant_couverture NUMERIC(12, 2) DEFAULT NULL, frais_assurance NUMERIC(8, 2) DEFAULT NULL, frais_dossier NUMERIC(8, 2) DEFAULT NULL, date_activation DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', date_expiration DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', date_resiliation DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', conditions_particulieres LONGTEXT DEFAULT NULL, note_admin LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_B36F5E5EA6608732 (numero_contrat), INDEX IDX_B36F5E5EA76ED395 (user_id), UNIQUE INDEX UNIQ_B36F5E5E787B318 (demande_devis_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE credit_applications (id INT AUTO_INCREMENT NOT NULL, confirmation_hash VARCHAR(32) NOT NULL, reference_number VARCHAR(12) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(20) NOT NULL, birth_date DATE NOT NULL, nationality VARCHAR(100) NOT NULL, marital_status VARCHAR(50) NOT NULL, dependents INT NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(100) NOT NULL, postal_code VARCHAR(10) NOT NULL, country VARCHAR(100) NOT NULL, housing_type VARCHAR(50) NOT NULL, monthly_income NUMERIC(10, 2) NOT NULL, employment_type VARCHAR(50) NOT NULL, employer VARCHAR(255) DEFAULT NULL, job_title VARCHAR(255) DEFAULT NULL, employment_start_date DATE DEFAULT NULL, monthly_expenses NUMERIC(10, 2) NOT NULL, existing_loans NUMERIC(10, 2) DEFAULT NULL, bank_name VARCHAR(255) NOT NULL, account_number VARCHAR(50) DEFAULT NULL, loan_amount NUMERIC(12, 2) NOT NULL, duration INT NOT NULL, duration_unit VARCHAR(255) NOT NULL, credit_type VARCHAR(255) NOT NULL, monthly_payment NUMERIC(10, 2) NOT NULL, total_cost NUMERIC(12, 2) NOT NULL, terms_accepted TINYINT(1) NOT NULL, data_processing_accepted TINYINT(1) NOT NULL, marketing_accepted TINYINT(1) NOT NULL, status VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', notes LONGTEXT DEFAULT NULL, contract_path VARCHAR(255) DEFAULT NULL, resend_count INT DEFAULT NULL, UNIQUE INDEX UNIQ_D13C7CBA64F6BFE (confirmation_hash), UNIQUE INDEX UNIQ_D13C7CBA8BF1AE50 (reference_number), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande_devis (id INT AUTO_INCREMENT NOT NULL, numero_devis VARCHAR(50) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, email VARCHAR(180) NOT NULL, telephone VARCHAR(20) NOT NULL, type_assurance VARCHAR(255) NOT NULL, preference_contact VARCHAR(20) NOT NULL, commentaires LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', statut VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_7DF946022478EE16 (numero_devis), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE demande_devis_credit_association (id INT AUTO_INCREMENT NOT NULL, demande_devis_id INT NOT NULL, credit_application_id INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', notes LONGTEXT DEFAULT NULL, is_active TINYINT(1) NOT NULL, INDEX IDX_D88E3A20787B318 (demande_devis_id), INDEX IDX_D88E3A20C9F772CD (credit_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE documents (id INT AUTO_INCREMENT NOT NULL, owner_id INT NOT NULL, verified_by_id INT DEFAULT NULL, credit_application_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, file_hash VARCHAR(64) NOT NULL, type VARCHAR(100) NOT NULL, category VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, description LONGTEXT DEFAULT NULL, expiry_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', verified_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', metadata JSON DEFAULT NULL, rejection_reason LONGTEXT DEFAULT NULL, is_confidential TINYINT(1) NOT NULL, is_archived TINYINT(1) NOT NULL, INDEX IDX_A2B072887E3C61F9 (owner_id), INDEX IDX_A2B0728869F4B775 (verified_by_id), INDEX IDX_A2B07288C9F772CD (credit_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kyc_document (id INT AUTO_INCREMENT NOT NULL, kyc_submission_id INT NOT NULL, type VARCHAR(50) NOT NULL, filename VARCHAR(255) NOT NULL, original_name VARCHAR(255) NOT NULL, mime_type VARCHAR(50) NOT NULL, file_size INT NOT NULL, uploaded_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_8D0A06D4C1C8502E (kyc_submission_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE kyc_submission (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, processed_by_id INT DEFAULT NULL, status VARCHAR(20) NOT NULL, submitted_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', admin_notes LONGTEXT DEFAULT NULL, submission_locale VARCHAR(5) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_A33A1EF0A76ED395 (user_id), INDEX IDX_A33A1EF02FFD4FD3 (processed_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE loan_payments (id INT AUTO_INCREMENT NOT NULL, loan_id INT NOT NULL, transaction_id INT DEFAULT NULL, payment_number VARCHAR(50) NOT NULL, amount NUMERIC(15, 2) NOT NULL, principal_amount NUMERIC(15, 2) NOT NULL, interest_amount NUMERIC(15, 2) NOT NULL, fee_amount NUMERIC(15, 2) DEFAULT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, due_date DATE NOT NULL, paid_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', scheduled_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', notes LONGTEXT DEFAULT NULL, metadata JSON DEFAULT NULL, UNIQUE INDEX UNIQ_32946199B3A884C2 (payment_number), INDEX IDX_32946199CE73868F (loan_id), INDEX IDX_329461992FC0CB0F (transaction_id), INDEX idx_loan_payment_due_date (due_date), INDEX idx_loan_payment_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE loans (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, credit_application_id INT DEFAULT NULL, loan_number VARCHAR(50) NOT NULL, amount NUMERIC(15, 2) NOT NULL, remaining_amount NUMERIC(15, 2) NOT NULL, monthly_payment NUMERIC(15, 2) NOT NULL, interest_rate NUMERIC(5, 4) NOT NULL, term_months INT NOT NULL, remaining_months INT NOT NULL, type VARCHAR(50) NOT NULL, status VARCHAR(20) NOT NULL, purpose LONGTEXT DEFAULT NULL, approved_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', disbursed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', first_payment_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', next_payment_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', last_payment_date DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', terms JSON DEFAULT NULL, total_interest NUMERIC(15, 2) NOT NULL, total_paid NUMERIC(15, 2) NOT NULL, missed_payments INT NOT NULL, UNIQUE INDEX UNIQ_82C24DBC6D13EA29 (loan_number), INDEX IDX_82C24DBC9B6B5FBA (account_id), INDEX IDX_82C24DBCC9F772CD (credit_application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE notifications (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) NOT NULL, message LONGTEXT NOT NULL, type VARCHAR(50) NOT NULL, is_read TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', read_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_6000B0D3A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE reset_password_request (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, selector VARCHAR(20) NOT NULL, hashed_token VARCHAR(100) NOT NULL, requested_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7CE748AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_account_card (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8DD5584F9B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_account_credit (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_5A51F2999B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_account_insurance (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_46D24FD9B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sub_account_savings (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_C1913B7A9B6B5FBA (account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transactions (id INT AUTO_INCREMENT NOT NULL, account_id INT NOT NULL, destination_account_id INT DEFAULT NULL, initiated_by_id INT DEFAULT NULL, reference VARCHAR(50) NOT NULL, amount NUMERIC(15, 2) NOT NULL, type VARCHAR(50) NOT NULL, category VARCHAR(100) NOT NULL, status VARCHAR(20) NOT NULL, description LONGTEXT DEFAULT NULL, notes LONGTEXT DEFAULT NULL, balance_after NUMERIC(15, 2) DEFAULT NULL, currency VARCHAR(3) NOT NULL, processed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', metadata JSON DEFAULT NULL, UNIQUE INDEX UNIQ_EAA81A4CAEA34913 (reference), INDEX IDX_EAA81A4C9B6B5FBA (account_id), INDEX IDX_EAA81A4CC652C408 (destination_account_id), INDEX IDX_EAA81A4CC4EF1FC7 (initiated_by_id), INDEX idx_transaction_created_at (created_at), INDEX idx_transaction_type (type), INDEX idx_transaction_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transfer_attempts (id INT AUTO_INCREMENT NOT NULL, transfer_id INT NOT NULL, transfer_code_id INT NOT NULL, attempted_code VARCHAR(9) NOT NULL, is_success TINYINT(1) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, attempted_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_5E76CA0E537048AF (transfer_id), INDEX IDX_5E76CA0E986F8C5C (transfer_code_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transfer_codes (id INT AUTO_INCREMENT NOT NULL, transfer_id INT NOT NULL, code_order INT NOT NULL, code_name VARCHAR(255) NOT NULL, code_value VARCHAR(9) NOT NULL, status VARCHAR(20) NOT NULL, failed_attempts INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', validated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_46293415537048AF (transfer_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transfers (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, destination_account_id INT NOT NULL, amount NUMERIC(15, 2) NOT NULL, status VARCHAR(20) NOT NULL, current_code_index INT NOT NULL, failed_attempts_total INT NOT NULL, is_account_blocked TINYINT(1) NOT NULL, description VARCHAR(500) DEFAULT NULL, reference VARCHAR(20) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', executed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_802A3918A76ED395 (user_id), INDEX IDX_802A3918C652C408 (destination_account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE `user` (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, is_verified TINYINT(1) NOT NULL, activation_token VARCHAR(255) DEFAULT NULL, activation_token_expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', last_login_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', phone VARCHAR(20) DEFAULT NULL, birth_date DATE DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, status VARCHAR(20) DEFAULT NULL, password_changed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', email_verified TINYINT(1) NOT NULL, two_factor_enabled TINYINT(1) NOT NULL, city VARCHAR(100) DEFAULT NULL, postal_code VARCHAR(10) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, language VARCHAR(5) DEFAULT NULL, currency VARCHAR(3) DEFAULT NULL, timezone VARCHAR(50) DEFAULT NULL, profile_picture VARCHAR(255) DEFAULT NULL, updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', pending_email VARCHAR(180) DEFAULT NULL, email_verification_token VARCHAR(255) DEFAULT NULL, email_verification_token_expires_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE accounts ADD CONSTRAINT FK_CAC89EAC7E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE amortization_schedule ADD CONSTRAINT FK_124FDE36C9F772CD FOREIGN KEY (credit_application_id) REFERENCES credit_applications (id)');
        $this->addSql('ALTER TABLE bank_accounts ADD CONSTRAINT FK_FB88842BA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE card_oppositions ADD CONSTRAINT FK_89A0F8C24ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id)');
        $this->addSql('ALTER TABLE card_oppositions ADD CONSTRAINT FK_89A0F8C24DA1E751 FOREIGN KEY (requested_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE card_oppositions ADD CONSTRAINT FK_89A0F8C22FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE card_subscriptions ADD CONSTRAINT FK_740D4320A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE card_subscriptions ADD CONSTRAINT FK_740D43209B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE card_subscriptions ADD CONSTRAINT FK_740D43202FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE card_subscriptions ADD CONSTRAINT FK_740D43204ACC9A20 FOREIGN KEY (card_id) REFERENCES cards (id)');
        $this->addSql('ALTER TABLE cards ADD CONSTRAINT FK_4C258FD9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE contract_fees ADD CONSTRAINT FK_C8E68F04C9F772CD FOREIGN KEY (credit_application_id) REFERENCES credit_applications (id)');
        $this->addSql('ALTER TABLE contract_subscriptions ADD CONSTRAINT FK_852C0BD9F43F9851 FOREIGN KEY (card_subscription_id) REFERENCES card_subscriptions (id)');
        $this->addSql('ALTER TABLE contrat_assurance ADD CONSTRAINT FK_B36F5E5EA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE contrat_assurance ADD CONSTRAINT FK_B36F5E5E787B318 FOREIGN KEY (demande_devis_id) REFERENCES demande_devis (id)');
        $this->addSql('ALTER TABLE demande_devis_credit_association ADD CONSTRAINT FK_D88E3A20787B318 FOREIGN KEY (demande_devis_id) REFERENCES demande_devis (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE demande_devis_credit_association ADD CONSTRAINT FK_D88E3A20C9F772CD FOREIGN KEY (credit_application_id) REFERENCES credit_applications (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B072887E3C61F9 FOREIGN KEY (owner_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B0728869F4B775 FOREIGN KEY (verified_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B07288C9F772CD FOREIGN KEY (credit_application_id) REFERENCES credit_applications (id)');
        $this->addSql('ALTER TABLE kyc_document ADD CONSTRAINT FK_8D0A06D4C1C8502E FOREIGN KEY (kyc_submission_id) REFERENCES kyc_submission (id)');
        $this->addSql('ALTER TABLE kyc_submission ADD CONSTRAINT FK_A33A1EF0A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE kyc_submission ADD CONSTRAINT FK_A33A1EF02FFD4FD3 FOREIGN KEY (processed_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE loan_payments ADD CONSTRAINT FK_32946199CE73868F FOREIGN KEY (loan_id) REFERENCES loans (id)');
        $this->addSql('ALTER TABLE loan_payments ADD CONSTRAINT FK_329461992FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transactions (id)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBC9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE loans ADD CONSTRAINT FK_82C24DBCC9F772CD FOREIGN KEY (credit_application_id) REFERENCES credit_applications (id)');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE reset_password_request ADD CONSTRAINT FK_7CE748AA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE sub_account_card ADD CONSTRAINT FK_8DD5584F9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE sub_account_credit ADD CONSTRAINT FK_5A51F2999B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE sub_account_insurance ADD CONSTRAINT FK_46D24FD9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE sub_account_savings ADD CONSTRAINT FK_C1913B7A9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4C9B6B5FBA FOREIGN KEY (account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CC652C408 FOREIGN KEY (destination_account_id) REFERENCES accounts (id)');
        $this->addSql('ALTER TABLE transactions ADD CONSTRAINT FK_EAA81A4CC4EF1FC7 FOREIGN KEY (initiated_by_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE transfer_attempts ADD CONSTRAINT FK_5E76CA0E537048AF FOREIGN KEY (transfer_id) REFERENCES transfers (id)');
        $this->addSql('ALTER TABLE transfer_attempts ADD CONSTRAINT FK_5E76CA0E986F8C5C FOREIGN KEY (transfer_code_id) REFERENCES transfer_codes (id)');
        $this->addSql('ALTER TABLE transfer_codes ADD CONSTRAINT FK_46293415537048AF FOREIGN KEY (transfer_id) REFERENCES transfers (id)');
        $this->addSql('ALTER TABLE transfers ADD CONSTRAINT FK_802A3918A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id)');
        $this->addSql('ALTER TABLE transfers ADD CONSTRAINT FK_802A3918C652C408 FOREIGN KEY (destination_account_id) REFERENCES bank_accounts (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE accounts DROP FOREIGN KEY FK_CAC89EAC7E3C61F9');
        $this->addSql('ALTER TABLE amortization_schedule DROP FOREIGN KEY FK_124FDE36C9F772CD');
        $this->addSql('ALTER TABLE bank_accounts DROP FOREIGN KEY FK_FB88842BA76ED395');
        $this->addSql('ALTER TABLE card_oppositions DROP FOREIGN KEY FK_89A0F8C24ACC9A20');
        $this->addSql('ALTER TABLE card_oppositions DROP FOREIGN KEY FK_89A0F8C24DA1E751');
        $this->addSql('ALTER TABLE card_oppositions DROP FOREIGN KEY FK_89A0F8C22FFD4FD3');
        $this->addSql('ALTER TABLE card_subscriptions DROP FOREIGN KEY FK_740D4320A76ED395');
        $this->addSql('ALTER TABLE card_subscriptions DROP FOREIGN KEY FK_740D43209B6B5FBA');
        $this->addSql('ALTER TABLE card_subscriptions DROP FOREIGN KEY FK_740D43202FFD4FD3');
        $this->addSql('ALTER TABLE card_subscriptions DROP FOREIGN KEY FK_740D43204ACC9A20');
        $this->addSql('ALTER TABLE cards DROP FOREIGN KEY FK_4C258FD9B6B5FBA');
        $this->addSql('ALTER TABLE contract_fees DROP FOREIGN KEY FK_C8E68F04C9F772CD');
        $this->addSql('ALTER TABLE contract_subscriptions DROP FOREIGN KEY FK_852C0BD9F43F9851');
        $this->addSql('ALTER TABLE contrat_assurance DROP FOREIGN KEY FK_B36F5E5EA76ED395');
        $this->addSql('ALTER TABLE contrat_assurance DROP FOREIGN KEY FK_B36F5E5E787B318');
        $this->addSql('ALTER TABLE demande_devis_credit_association DROP FOREIGN KEY FK_D88E3A20787B318');
        $this->addSql('ALTER TABLE demande_devis_credit_association DROP FOREIGN KEY FK_D88E3A20C9F772CD');
        $this->addSql('ALTER TABLE documents DROP FOREIGN KEY FK_A2B072887E3C61F9');
        $this->addSql('ALTER TABLE documents DROP FOREIGN KEY FK_A2B0728869F4B775');
        $this->addSql('ALTER TABLE documents DROP FOREIGN KEY FK_A2B07288C9F772CD');
        $this->addSql('ALTER TABLE kyc_document DROP FOREIGN KEY FK_8D0A06D4C1C8502E');
        $this->addSql('ALTER TABLE kyc_submission DROP FOREIGN KEY FK_A33A1EF0A76ED395');
        $this->addSql('ALTER TABLE kyc_submission DROP FOREIGN KEY FK_A33A1EF02FFD4FD3');
        $this->addSql('ALTER TABLE loan_payments DROP FOREIGN KEY FK_32946199CE73868F');
        $this->addSql('ALTER TABLE loan_payments DROP FOREIGN KEY FK_329461992FC0CB0F');
        $this->addSql('ALTER TABLE loans DROP FOREIGN KEY FK_82C24DBC9B6B5FBA');
        $this->addSql('ALTER TABLE loans DROP FOREIGN KEY FK_82C24DBCC9F772CD');
        $this->addSql('ALTER TABLE notifications DROP FOREIGN KEY FK_6000B0D3A76ED395');
        $this->addSql('ALTER TABLE reset_password_request DROP FOREIGN KEY FK_7CE748AA76ED395');
        $this->addSql('ALTER TABLE sub_account_card DROP FOREIGN KEY FK_8DD5584F9B6B5FBA');
        $this->addSql('ALTER TABLE sub_account_credit DROP FOREIGN KEY FK_5A51F2999B6B5FBA');
        $this->addSql('ALTER TABLE sub_account_insurance DROP FOREIGN KEY FK_46D24FD9B6B5FBA');
        $this->addSql('ALTER TABLE sub_account_savings DROP FOREIGN KEY FK_C1913B7A9B6B5FBA');
        $this->addSql('ALTER TABLE transactions DROP FOREIGN KEY FK_EAA81A4C9B6B5FBA');
        $this->addSql('ALTER TABLE transactions DROP FOREIGN KEY FK_EAA81A4CC652C408');
        $this->addSql('ALTER TABLE transactions DROP FOREIGN KEY FK_EAA81A4CC4EF1FC7');
        $this->addSql('ALTER TABLE transfer_attempts DROP FOREIGN KEY FK_5E76CA0E537048AF');
        $this->addSql('ALTER TABLE transfer_attempts DROP FOREIGN KEY FK_5E76CA0E986F8C5C');
        $this->addSql('ALTER TABLE transfer_codes DROP FOREIGN KEY FK_46293415537048AF');
        $this->addSql('ALTER TABLE transfers DROP FOREIGN KEY FK_802A3918A76ED395');
        $this->addSql('ALTER TABLE transfers DROP FOREIGN KEY FK_802A3918C652C408');
        $this->addSql('DROP TABLE accounts');
        $this->addSql('DROP TABLE amortization_schedule');
        $this->addSql('DROP TABLE bank_accounts');
        $this->addSql('DROP TABLE card_oppositions');
        $this->addSql('DROP TABLE card_subscriptions');
        $this->addSql('DROP TABLE cards');
        $this->addSql('DROP TABLE company_settings');
        $this->addSql('DROP TABLE contract_fees');
        $this->addSql('DROP TABLE contract_subscriptions');
        $this->addSql('DROP TABLE contrat_assurance');
        $this->addSql('DROP TABLE credit_applications');
        $this->addSql('DROP TABLE demande_devis');
        $this->addSql('DROP TABLE demande_devis_credit_association');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE kyc_document');
        $this->addSql('DROP TABLE kyc_submission');
        $this->addSql('DROP TABLE loan_payments');
        $this->addSql('DROP TABLE loans');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE reset_password_request');
        $this->addSql('DROP TABLE sub_account_card');
        $this->addSql('DROP TABLE sub_account_credit');
        $this->addSql('DROP TABLE sub_account_insurance');
        $this->addSql('DROP TABLE sub_account_savings');
        $this->addSql('DROP TABLE transactions');
        $this->addSql('DROP TABLE transfer_attempts');
        $this->addSql('DROP TABLE transfer_codes');
        $this->addSql('DROP TABLE transfers');
        $this->addSql('DROP TABLE `user`');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
